INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i7-9700K', '16GB DDR4', 'NVIDIA GeForce RTX 2080', '1TB SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 5 3600', '8GB DDR4', 'AMD Radeon RX 5700', '512GB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i5-10600K', '32GB DDR4', 'NVIDIA GeForce GTX 1660 Ti', '2TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 7 5800X', '16GB DDR4', 'NVIDIA GeForce RTX 3060', '1TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i9-10900K', '64GB DDR4', 'AMD Radeon RX 6900 XT', '4TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 9 5900X', '32GB DDR4', 'NVIDIA GeForce RTX 3080', '2TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i7-8700K', '16GB DDR4', 'AMD Radeon RX 5600 XT', '1TB SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 5 5600X', '16GB DDR4', 'NVIDIA GeForce GTX 1650', '512GB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i5-9600K', '8GB DDR4', 'NVIDIA GeForce GTX 1660 Super', '2TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 7 3700X', '32GB DDR4', 'AMD Radeon RX 5700 XT', '1TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i9-9900K', '64GB DDR4', 'NVIDIA GeForce RTX 3090', '4TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 9 5950X', '32GB DDR4', 'NVIDIA GeForce RTX 3070', '2TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i7-9700', '16GB DDR4', 'NVIDIA GeForce GTX 1650 Super', '1TB SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 5 3600X', '8GB DDR4', 'AMD Radeon RX 5500 XT', '512GB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i5-10600KF', '32GB DDR4', 'NVIDIA GeForce GTX 1660', '2TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 7 5800', '16GB DDR4', 'NVIDIA GeForce RTX 3060 Ti', '1TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i9-10900KF', '64GB DDR4', 'AMD Radeon RX 6800', '4TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 9 5900', '32GB DDR4', 'NVIDIA GeForce RTX 3080 Ti', '2TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i7-8700', '16GB DDR4', 'AMD Radeon RX 5600', '1TB SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 5 5600', '16GB DDR4', 'NVIDIA GeForce GTX 1650 Ti', '512GB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i5-9600', '8GB DDR4', 'NVIDIA GeForce GTX 1660', '2TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 7 3700', '32GB DDR4', 'AMD Radeon RX 5700', '1TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i9-9900', '64GB DDR4', 'NVIDIA GeForce RTX 3090 Ti', '4TB HDD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('AMD Ryzen 9 5950', '32GB DDR4', 'NVIDIA GeForce RTX 3070 Ti', '2TB NVMe SSD');
INSERT INTO komputery (Procesor, RAM, Karta, HDD) VALUES ('Intel Core i7-9700F', '16GB DDR4', 'NVIDIA GeForce GTX 1650', '1TB SSD');

INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Adam', 'Kowalski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Anna', 'Nowak');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Marcin', 'Wójcik');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Katarzyna', 'Kaczmarek');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Michał', 'Lewandowski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Magdalena', 'Jankowska');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Piotr', 'Mazur');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Monika', 'Kwiatkowska');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Tomasz', 'Krawczyk');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Natalia', 'Pawlak');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Bartosz', 'Wiśniewski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Karolina', 'Kaczmarczyk');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Krzysztof', 'Kalinowski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Alicja', 'Czarnecka');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Wojciech', 'Głowacki');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Agnieszka', 'Sikora');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Robert', 'Kowalczyk');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Aleksandra', 'Baran');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Daniel', 'Dąbrowski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Patrycja', 'Piotrowska');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Kamil', 'Kaczorowski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Dominika', 'Nowicka');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Grzegorz', 'Jasinski');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Martyna', 'Kucharska');
INSERT INTO pracownicy (Imie, Nazwisko) VALUES ('Rafał', 'Witkowski');

INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2690v4', '128GB DDR4', 'NVIDIA Quadro P5000', '4TB SAS', '1');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7742', '256GB DDR4', 'AMD Radeon Pro WX 9100', '8TB SAS', '2');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Gold 6240', '64GB DDR4', 'NVIDIA Tesla V100', '2TB NVMe', '3');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7551P', '128GB DDR4', 'AMD Radeon Pro WX 8200', '4TB SATA', '4');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2680v3', '32GB DDR4', 'NVIDIA Quadro P4000', '1TB SATA', '5');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7302P', '64GB DDR4', 'AMD Radeon Pro WX 7100', '2TB SAS', '6');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Silver 4214', '32GB DDR4', 'NVIDIA Tesla T4', '1TB NVMe', '7');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7272', '128GB DDR4', 'AMD Radeon Pro WX 5100', '4TB SATA', '8');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2667v4', '64GB DDR4', 'NVIDIA Quadro P2000', '2TB SAS', '9');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7232P', '32GB DDR4', 'AMD Radeon Pro WX 3200', '1TB SATA', '10');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Gold 5218', '128GB DDR4', 'NVIDIA Tesla P100', '4TB NVMe', '11');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7702P', '256GB DDR4', 'AMD Radeon Pro WX 9100', '8TB SAS', '12');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2698v3', '64GB DDR4', 'NVIDIA Quadro P5000', '2TB SAS', '13');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7402P', '128GB DDR4', 'AMD Radeon Pro WX 8200', '4TB SATA', '14');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Gold 6146', '32GB DDR4', 'NVIDIA Tesla V100', '1TB SATA', '15');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7601', '64GB DDR4', 'AMD Radeon Pro WX 7100', '2TB SAS', '16');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Silver 4210', '32GB DDR4', 'NVIDIA Tesla T4', '1TB NVMe', '17');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7271', '128GB DDR4', 'AMD Radeon Pro WX 5100', '4TB SATA', '18');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2650v4', '64GB DDR4', 'NVIDIA Quadro P2000', '2TB SAS', '19');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7231P', '32GB DDR4', 'AMD Radeon Pro WX 3200', '1TB SATA', '20');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Gold 5217', '128GB DDR4', 'NVIDIA Tesla P100', '4TB NVMe', '21');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7702', '256GB DDR4', 'AMD Radeon Pro WX 9100', '8TB SAS', '22');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon E5-2697v3', '64GB DDR4', 'NVIDIA Quadro P5000', '2TB SAS', '23');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('AMD EPYC 7402', '128GB DDR4', 'AMD Radeon Pro WX 8200', '4TB SATA', '24');
INSERT INTO serwery (Procesor, RAM, Karta, HDD, Administrator) VALUES ('Intel Xeon Gold 6144', '32GB DDR4', 'NVIDIA Tesla V100', '1TB SATA', '25');